### ISSUE TITLE
Lobry–Rosso–Flandrois model

### ISSUE THREAD

**Issue by Fjalladis** [padpadpadpad/rTPC#47]
Hi! 
I'm working on thermal ecology of insects and applying your great rTPC pipeline! However, I wanted to suggest an additional model, the Lobry–Rosso–Flandrois (LRF) model. Ratkowsky et al. (2016) compared several models and came to following conclusions:

"Another nonlinear regression model, not previously considered in
population entomology, is the Lobry–Rosso–Flandrois model, the shape of which is very close to that of the
Ratkowsky model in the suboptimal temperature range, but which has the added advantage that all four of its
parameters have biological meaning."

"We can conclude that the LRF model is the best of the five models
studied, providing close-to-linear least squares estimates to data
on the development of insects and mites."

I'm very curious to test the performance of the LRF model in my study system, but it would be a great advantage to have it included in the rTPC pipeline. Maybe you're interested in looking into this model?

All the best,
Kim
______
Ratkowsky, David & Reddy, Gadi. (2017). Empirical Model With Excellent Statistical Properties for Describing Temperature-Dependent Developmental Rates of Insects and Mites. Annals of the Entomological Society of America. 110. 302-309. 10.1093/aesa/saw098.

**Comment by padpadpadpad** [comment]
Hi @Fjalladis.

It is rare that there is a model that I have not come across before! I am happy to try incorporate the model into rTPC's framework of functions.

Will put updates in here as we go.

- [ ]  add function for fitting the curve
- [ ]  include in helper functions (`get_model_names()`, `get_start_vals()`, `get_lower_lims()`, `get_upper_lims()`.
- [ ]  add to readme.

**Comment by Fjalladis** [comment]
Thank you so much! Very excited to see how it goes. I'm currently using the Ratkowsky model, but the LRF model would be a great update.

**Comment by padpadpadpad** [comment]
This should be available on the latest commit. 😄  I added it as `lrf_1991()` and it should be included in all the helper functions now.

Out of interest why do you like the Ratkowsky model? I do not like its tendency to go a bit crazy after t<sub>max</sub> so have not used it much.

**Comment by Fjalladis** [comment]
Woow, that was quick, thank you so much for implementing this model!! Highly appreciated!
I just quickly ran it based on my data, so far it doesn't give me a topt, but I will try to fit it :)

Ratkowsky seemed to be the closest to the LRF model which is recommended for insects, and as I only have data very close to the thermal optimum (far away from tmax) the fit works quite well, although I was not completely satisfied with the TPC turning out surprisingly symmetrical...
