### ISSUE TITLE
vignettes not installing

### ISSUE THREAD

**Issue by mikegilchrist** [padpadpadpad/rTPC#48]
I expected the vignettes mentioned in the documentation to be installed when installing the package from github, but they don't appear to be.  Am I missing something, such as a flag in the `README.md` installation command?

**Comment by padpadpadpad** [comment]
Lots of the vignettes are computationally intensive. If you want to compile them you need `build_vignettes = TRUE` in the `install_github()` command. It took 8 minutes to install them on my machine (2016 Macbook Pro).

Personally I use online vignettes much more than the ones compiled within R, so I do not tend to build them and use them in my workflow.

**Comment by mikegilchrist** [comment]
Okay. Thanks for enlightening me on how to build them.
