### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by juanharagon** [padpadpadpad/rTPC#53]
HI! I'm trying to run the"test" script from the supplementary materials, and im getting an error in line 139:

this line has the following code:

extra_params <- d_stack %>%
  mutate(., est = map(output, est_params)) %>%
  select(., -c(data, output)) %>%
  unnest(., est) %>%
  mutate(., rmax = round(rmax, 2))

when I try to run it I get the following:

Error in `mutate()`:
ℹ In argument: `est = map(output, est_params)`.
Caused by error:
! object 'est_params' not found.

Culd you help fixing this issue?

**Comment by padpadpadpad** [comment]
Hi @juanharagon,

The test script should not really be here anymore! **est_params()** does not exist because I changed it to **calc_params()** - https://padpadpadpad.github.io/rTPC/reference/calc_params.html

Would really recommending following the vignettes instead of test.R.

Cheers
Dan
