### ISSUE TITLE
Predictability of model names

### ISSUE THREAD

**Issue by fwimp** [padpadpadpad/rTPC#63]
As part of #59 there are a lot of models which are "simplified x" and "modified y".

The current naming scheme would produce `modifiedextendedbriere2_1999()` as a model name, which feels a bit unintuitive as if you don't know what order the extended and modified go in.

Instead I might suggest switching to a naming scheme of `<model><modification><modification>_YYYY()`.

In this scheme if you have rTPC loaded and want to use some sort of briere function, you could type "briere(TAB)" and get autocompletes for:
- `briere1`
- `briere1simplified`
- `briere2`
- `briere2simplified`
- `briereextended`
- `briereextendedsimplified`

This does bring up one issue that `modifiedgaussian_2006` has been in the package since 2019, so people may well be using it.

A method of dealing with this is for old models to include the old function names as deprecated aliases for a time until we eventually remove them.

**Comment by padpadpadpad** [comment]
Yea so the renaming definitely makes sense to me, and is how I named sharpeschoolhigh, sharpeschoolfull, sharpeschoollow. I would hope no one is using modified gaussian as I generally think it is bad, but there is a chance people are! 

I agree maybe doubling up but removing it from vignettes is the way to go for a while, and just say we will remove it at a specific date.

**Comment by fwimp** [comment]
Perfect, Okay I'll do the changeover for modifiedgaussian and simplifiedbetatype on my working branch.

I'll submit a PR when I'm done working today so that everything is in good working order when I'm away from my main computer, just in case the ol' laptop decides to have none of it.
